name: Update Data

on:
  schedule:
    # L'orario è in UTC. In Italia le estrazioni iniziano alle 20:00.
    # Eseguiamo lo script alle 20:15 e 20:45 UTC (ovvero 21:15 e 21:45 italiane)
    # per essere sicuri che i dati siano stati pubblicati sul sito.
    # Giorni: 2=Mar, 4=Gio, 5=Ven, 6=Sab
    - cron: '15,45 19,20 * * 2,4,5,6'
  workflow_dispatch: # Questo ti permette di avviare l'aggiornamento a mano per testare

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v3

      - name: Configura Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installa librerie necessarie
        run: pip install requests beautifulsoup4

      - name: Esegui lo script di scraping
        env:
          SCRAPE_DO_TOKEN: ${{ secrets.SCRAPE_DO_TOKEN }}
        run: python scrape_lotto.py

      - name: Salva i cambiamenti nel repository
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add storico_10elotto.csv
          # Il comando commit fallisce se non ci sono nuovi dati, usiamo || exit 0 per non dare errore
          git commit -m "Aggiornamento automatico estrazione $(date)" || exit 0
          git push
